inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

Metrics/LineLength:
  Max: 140

Airbnb/OptArgParameters:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Airbnb/SimpleUnless:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/AlignArguments:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'
