# -*- mode: dockerfile -*-
FROM ruby:2.5.3

RUN apt-get update -qq && \
    apt-get install -y build-essential \
                       libpq-dev \
                       nodejs

ENV APP_ROOT /bbq_site_matching
ENV LANG C.UTF-8
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

COPY . $APP_ROOT
RUN bundle install
