# -*- mode: dockerfile -*-
FROM ruby:2.5.3

RUN apt-get update -qq && \
    apt-get install -y build-essential \
                       libpq-dev \
                       nodejs

RUN mkdir /usr/src/camp_site_matching
ENV APP_ROOT /usr/src/camp_site_matching
WORKDIR $APP_ROOT
ENV LANG C.UTF-8

ADD ./Gemfile $APP_ROOT/Gemfile
ADD ./Gemfile.lock $APP_ROOT/Gemfile.lock

RUN gem install bundler -v 1.17.3
RUN bundle install
ADD . $APP_ROOT
