version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.3-node-browsers
      environment:
        BUNDLER_VERSION: 1.17.3
        RAILS_ENV: test
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: '%'
    working_directory: ~/bbq_site_matching
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          gem install bundler -v 1.17.3
          bundle install --jobs=4 --retry=3 --path vendor/bundle
          gem install rspec_junit_formatter
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    - run: mv config/database.yml.ci config/database.yml
    - run: bundle exec rails db:create
    - run: bundle exec rails db:schema:load
    - run:
        name: Rubocop
        command: bundle exec rubocop
    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"
          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/ryuji2020/bbq_site_matching/compare/23f4b2fce7a4f73f8768bf4cd9831f61fa8948c2...23f4b2fce7a4f73f8768bf4cd9831f61fa8948c2
workflows:
  version: 2
  workflow:
    jobs:
    - build
